import "@sqlite.org/sqlite-wasm";
// Module Augmentation
// Generated by GitHub Copilot
declare module "@sqlite.org/sqlite-wasm" {
  export interface Config {
    onready?: (promiser?: () => any) => void;
    worker?: Worker | (() => Worker);
    generateMessageId?: (messageObject: any) => string;
    debug?: (...args: any[]) => void;
    onunhandled?: (event: MessageEvent) => void;
  }

  export function sqlite3Worker1Promiser(): any;
  export function sqlite3Worker1Promiser(config: Config): any;
  export function sqlite3Worker1Promiser(
    onready: (promiser?: () => any) => void
  ): any;

  export var defaultConfig: Config;
}
